import type { Metadata } from "next";
import "./globals.css";

import { generalSans, ppEditorial } from "./assets/fonts/font";

import ReactQueryProvider from "./provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` font-GeneralSans ${generalSans.variable} ${ppEditorial.variable}  `}
      >
        <ReactQueryProvider> {children}</ReactQueryProvider>
        {/* <main className="font-GeneralSans ">{children}</main> */}
      </body>
    </html>
  );
}
