import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header";
import { generalSans, ppEditorial } from "./assets/fonts/font";
import NavBar from "@/components/layout/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${generalSans.variable} ${ppEditorial.variable}  `}>
        <Header />
        <NavBar />
        <main className="font-GeneralSans ">{children}</main>
      </body>
    </html>
  );
}
