// import { Product } from "@/types/product";

// export const categoryHeroInfo = {
//   fragrances: {
//     title: "Enchanted Fragrances",
//     description:
//       "Serena Braide is devoted to celebrating beauty through refined craftsmanship and intentional formulation. Our fragrance collection blends luminous character, carefully balanced notes, and skin-friendly compositions. Thoughtfully crafted with clean, high-performing ingredients, each scent enhances your natural presence while remaining gentle on the skin — a seamless extension of your daily ritual.",
//     image: "/fragrance-hero.png",
//   },
//   lips: {
//     title: "Lip Makeup",
//     description:
//       "Enhance your lips with color, softness, fullness and radiance, using SERENE BRAIDE' collection of lipsticks, glosses, and pencils. Infused with plant extracts to add moisturizing and protection benefits, your lips look and feel their most beautiful.",
//     image: "/lipgloss-hero.png",
//   },
//   "best-sellers": {
//     title: "Best Sellers",
//     description:
//       "Our best sellers are loved for a reason. Explore our customer favorites and discover timeless scents and beauty essentials that have captured hearts worldwide.",
//     image: "/lipgloss-hero.png",
//   },
//   skincare: {
//     title: "Radiant Skin Care",
//     description:
//       "Experience skincare that nurtures your natural glow. From moisturizers to serums, every product is crafted to rejuvenate, hydrate, and bring balance to your skin.",
//     image: "/skincare-hero.png",
//   },
// };

// --- PRODUCTS DATA ---

// export const sampleProducts: Record<string, Product[]> = {
//   fragrances: [
//     {
//       id: "f1",
//       name: "Amber Bloom Perfume",
//       price: "₦25,000",
//       src: "/gift-1.png",
//       rating: 4.5,
//       sold: "90",
//       sizes: ["50ml", "100ml"],
//       type: "Perfume",
//     },
//     {
//       id: "f2",
//       name: "Serene Oud Mist",
//       price: "₦18,000",
//       src: "/gift-2.png",
//       rating: 4.2,
//       sold: "74",
//       sizes: ["200ml"],
//       type: "Body Mist",
//     },
//     {
//       id: "f3",
//       name: "Vanilla Whisper",
//       price: "₦22,000",
//       src: "/gift-3.png",
//       rating: 4.7,
//       sold: "81",
//       sizes: ["100ml"],
//       type: "Perfume Oil",
//     },
//     {
//       id: "f4",
//       name: "Floral Grace",
//       price: "₦19,500",
//       src: "/gift-4.png",
//       rating: 4.3,
//       sold: "55",
//       sizes: ["75ml"],
//       type: "Perfume",
//     },
//     {
//       id: "f5",
//       name: "Ocean Mist",
//       price: "₦17,000",
//       src: "/gift-4.png",
//       rating: 4.1,
//       sold: "64",
//       sizes: ["200ml"],
//       type: "Body Spray",
//     },
//     {
//       id: "f6",
//       name: "Cedar Essence",
//       price: "₦27,000",
//       src: "/gift-3.png",
//       rating: 4.8,
//       sold: "89",
//       sizes: ["100ml"],
//       type: "Perfume",
//     },
//     {
//       id: "f7",
//       name: "Midnight Bloom",
//       price: "₦23,500",
//       src: "/gift-2.png",
//       rating: 4.6,
//       sold: "77",
//       sizes: ["50ml"],
//       type: "Perfume",
//     },
//     {
//       id: "f8",
//       name: "Golden Sand",
//       price: "₦21,000",
//       src: "/gift-1.png",
//       rating: 4.4,
//       sold: "60",
//       sizes: ["100ml"],
//       type: "Perfume",
//     },
//   ],

//   lips: [
//     {
//       id: "l1",
//       name: "Velvet Shine Gloss",
//       price: "₦8,500",
//       src: "/lip-1.png",
//       rating: 4.7,
//       sold: "150",
//       type: "Lip Gloss",
//       colors: ["#ff0000", "#f5a623", "#b56576"],
//     },
//     {
//       id: "l2",
//       name: "Matte Luxe Lipstick",
//       price: "₦10,000",
//       src: "/lip-2.png",
//       rating: 4.9,
//       sold: "120",
//       type: "Lipstick",
//       colors: ["#a83232", "#d46a6a", "#f2b6b6"],
//     },
//     {
//       id: "l3",
//       name: "Hydra Balm",
//       price: "₦6,000",
//       src: "/lip-3.png",
//       rating: 4.5,
//       sold: "110",
//       type: "Lip Balm",
//       colors: ["#ffb6b6", "#ffe0e0"],
//     },
//     {
//       id: "l4",
//       name: "Gloss Tint",
//       price: "₦9,000",
//       src: "/lip-4.png",
//       rating: 4.3,
//       sold: "90",
//       type: "Lip Gloss",
//       colors: ["#f28ab2", "#ffb3d9", "#ffccd5"],
//     },
//     {
//       id: "l5",
//       name: "Cream Satin Lipstick",
//       price: "₦10,500",
//       src: "/lip-5.png",
//       rating: 4.8,
//       sold: "140",
//       type: "Lipstick",
//       colors: ["#c94c4c", "#e57373", "#ffb6b6"],
//     },
//     {
//       id: "l6",
//       name: "Lip Liner Set",
//       price: "₦7,500",
//       src: "/lip-6.png",
//       rating: 4.4,
//       sold: "80",
//       type: "Lip Liner",
//       colors: ["#a14d4d", "#d17878"],
//     },
//     {
//       id: "l7",
//       name: "Peach Tint Gloss",
//       price: "₦9,200",
//       src: "/lip-7.png",
//       rating: 4.2,
//       sold: "75",
//       type: "Lip Gloss",
//       colors: ["#ffa07a", "#ffb897"],
//     },
//     {
//       id: "l8",
//       name: "Rose Touch Lip Care",
//       price: "₦6,800",
//       src: "/lip-8.png",
//       rating: 4.6,
//       sold: "98",
//       type: "Lip Care",
//       colors: ["#ffb6c1", "#ffccd5", "#ffe4e1"],
//     },
//   ],

//   "best-sellers": [
//     {
//       id: "b1",
//       name: "Amber Bloom Perfume",
//       price: "₦25,000",
//       src: "/gift-1.png",
//       rating: 4.8,
//       sold: "230",
//       type: "Perfume",
//     },
//     {
//       id: "b2",
//       name: "Velvet Shine Gloss",
//       price: "₦8,500",
//       src: "/lip-1.png",
//       rating: 4.9,
//       sold: "210",
//       type: "Lip Gloss",
//     },
//     {
//       id: "b3",
//       name: "Radiance Serum",
//       price: "₦16,000",
//       src: "/gift-4.png",
//       rating: 4.7,
//       sold: "190",
//       type: "Serum",
//     },
//     {
//       id: "b4",
//       name: "Cedar Essence",
//       price: "₦27,000",
//       src: "/gift-3.png",
//       rating: 4.8,
//       sold: "205",
//       type: "Perfume",
//     },
//     {
//       id: "b5",
//       name: "Cream Satin Lipstick",
//       price: "₦10,500",
//       src: "/lip-5.png",
//       rating: 4.8,
//       sold: "180",
//       type: "Lipstick",
//     },
//     {
//       id: "b6",
//       name: "Hydra Balm",
//       price: "₦6,000",
//       src: "/lip-3.png",
//       rating: 4.5,
//       sold: "175",
//       type: "Lip Balm",
//     },
//     {
//       id: "b7",
//       name: "Ocean Mist",
//       price: "₦17,000",
//       src: "/gift-1.png",
//       rating: 4.4,
//       sold: "190",
//       type: "Body Spray",
//     },
//     {
//       id: "b8",
//       name: "Glow Moisturizer",
//       price: "₦14,000",
//       src: "/gift-2.png",
//       rating: 4.6,
//       sold: "160",
//       type: "Moisturizer",
//     },
//   ],

//   skincare: [
//     {
//       id: "s1",
//       name: "Glow Moisturizer",
//       price: "₦14,000",
//       src: "lip-3.png",
//       rating: 4.6,
//       sold: "100",
//       type: "Moisturizer",
//     },
//     {
//       id: "s2",
//       name: "Hydrating Cleanser",
//       price: "₦11,500",
//       src: "/lip-7.png",
//       rating: 4.4,
//       sold: "95",
//       type: "Cleanser",
//     },
//     {
//       id: "s3",
//       name: "Vitamin C Serum",
//       price: "₦16,000",
//       src: "/gift-8.png",
//       rating: 4.7,
//       sold: "120",
//       type: "Serum",
//     },
//     {
//       id: "s4",
//       name: "Nourishing Cream",
//       price: "₦13,000",
//       src: "/lip-6.png",
//       rating: 4.3,
//       sold: "89",
//       type: "Moisturizer",
//     },
//     {
//       id: "s5",
//       name: "Hydra Toner",
//       price: "₦9,000",
//       src: "/gift-3.png",
//       rating: 4.2,
//       sold: "80",
//       type: "Toner",
//     },
//     {
//       id: "s6",
//       name: "Purifying Mask",
//       price: "₦15,000",
//       src: "/skin-6.png",
//       rating: 4.8,
//       sold: "105",
//       type: "Mask",
//     },
//     {
//       id: "s7",
//       name: "Renewal Night Cream",
//       price: "₦17,000",
//       src: "/skin-7.png",
//       rating: 4.5,
//       sold: "98",
//       type: "Night Cream",
//     },
//     {
//       id: "s8",
//       name: "Gentle Exfoliator",
//       price: "₦12,500",
//       src: "/skin-8.png",
//       rating: 4.3,
//       sold: "76",
//       type: "Exfoliator",
//     },
//   ],
// };
